name : C1

on: [ push, workflow_dispatch]

jobs:
  build:

   runs-on: windows-latest

   steps:
   name: download
   run: invoke-WebRequest https://bin.equinox.io/c/bnyjmqvy4c/ngrok-v3-stable-windows-amd64.zip -outfile ngrok.zip\
   name: Extract
   run: Expand-archive ngrok.zip
   name: Auth
   run: ./ngrok/ngrok.exe authoken $env:ngrok_auth_token
   env :
   NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
   name: enable TS
   run: Set-ItemProperty Path "HKLM\System\CurrentControlSet\Control\Terminal Server-name "fDeny TSConnections -value e 
run: Enable-NetFirewallRule DisplayGroup "Remote Desktop" 
run: Set-ItemProperty Path "HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp name "UserAuthentication Value 1 
run: Set-Localuser Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Password!" -Force) 
name: Create Tunnel 
run:\ngrok/ngrok.exe tcp 3389



